#! /bin/bash

if [[ $1 == "deploy" ]]
then
   docker build -t arava-api . -f docker/api/Dockerfile || exit 1
   docker build -t arava-admin-api .  -f docker/admin/Dockerfile || exit 1

   docker tag arava-api registry.ndogga.com/arava/arava-api:latest || exit 1
   docker tag arava-admin-api registry.ndogga.com/arava/arava-admin-api:latest || exit 1

   docker push registry.ndogga.com/arava/arava-api:latest || exit 1
   docker push registry.ndogga.com/arava/arava-admin-api:latest || exit 1

   curl -X POST https://portainer.ndogga.com/api/webhooks/fef45523-c348-4f63-b48f-26e76778d796
   curl -X POST https://portainer.ndogga.com/api/webhooks/4a7646f3-0e48-4071-9f45-c6be79a5abf0

   echo "Successfully built and deployed to Portainer"
   exit 0
fi

echo "Available commands : deploy"
exit 1