#! /bin/bash

if [[ $1 == "deploy" ]]
then
   docker build -t arava-backend .
   docker tag arava-backend registry.ndogga.com/arava/arava-backend:latest
   docker push registry.ndogga.com/arava/arava-backend:latest
   curl -X POST https://portainer.ndogga.com/api/webhooks/fef45523-c348-4f63-b48f-26e76778d796
   exit 0
fi

echo "Available commands : deploy"
exit 1