version: '3.1'

services:
  arava-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
    - 10100:8080
    environment:
      SPRING_PROFILES_ACTIVE: staging
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres