version: '3.1'

services:
  arava-api:
    image: docker.artifactory.ndogga.com/arava/arava-api:latest
    restart: always
    ports:
      - 10100:8080
    environment:
      SPRING_PROFILES_ACTIVE: staging
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/arava
      SPRING_DATASOURCE_USERNAME: arava-admin
      SPRING_DATASOURCE_PASSWORD: Admin@rava
      ELASTICSEARCH_PASSWORD:
      JWT_SECRET:
  arava-admin-api:
    image: docker.artifactory.ndogga.com/arava/arava-admin-api:latest
    restart: always
    ports:
      - 10104:8080
    environment:
      SPRING_PROFILES_ACTIVE: staging
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/arava
      SPRING_DATASOURCE_USERNAME: arava-admin
      SPRING_DATASOURCE_PASSWORD: Admin@rava
      ELASTICSEARCH_PASSWORD:
      JWT_SECRET:
  arava-admin:
    image: docker.artifactory.ndogga.com/arava/arava-admin:latest
    restart: always
    ports:
      - 10103:5000
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=arava
      - POSTGRES_USER=arava-admin
      - POSTGRES_PASSWORD=Admin@rava
    ports:
      - 10106:5432