spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
  datasource:
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  main:
    allow-bean-definition-overriding: true
jwt:
  secret: ORM2XTeeOz2hRQXtGAyoERDwSfroZeaLoQw5axovlUVlP71mZ1GRgFsCt3sk7iR
  expiration: 3600
  token-type: "Bearer"
hibernate:
  search:
    default:
      indexmanager: elasticsearch
      elasticsearch:
        host: http://elasticsearch:9200
arava:
  search:
    max-similar-results: 20