
spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
  datasource:
    url: jdbc:postgresql://localhost:5432/arava
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  main:
    allow-bean-definition-overriding: true
  application:
    name: Arava Admin Api
jwt:
  secret: 268YXz7tkqYON3wpAfXFMIlDT8qmn4v01DvTllPIShKKizl7RV80W7SbTshpmPt
  expiration: 3600
  token-type: "Bearer"
hibernate:
  search:
    default:
      directory_provider: filesystem
      indexBase: /var/indexed_data/arava/default
arava:
  search:
    max-similar-results: 20
logging:
  file: logs/api.log
server:
  port: 8081