
spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
    default-property-inclusion: non_null
  datasource:
    url: jdbc:postgresql://private-db-postgresql-sgp1-41511-do-user-9413832-0.b.db.ondigitalocean.com:25061/arava?sslmode=require
    username: arava
    password: vs3v7n62tjqx5e4j
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        search:
          default_backend: es
          automatic_indexing:
            synchronization:
              strategy: async
          backends:
            es:
              type: elasticsearch
              hosts: "${elasticsearch.host}:${elasticsearch.port}"
              protocol: ${elasticsearch.protocol}
              index_defaults:
                lifecycle:
                  minimal_required_status: yellow
  main:
    allow-bean-definition-overriding: true
jwt:
  expiration: 604800
  token-type: "Bearer"
  secret: "268YXz7tkqYON3wpAfXFMIlDT8qmn4v01DvTllPIShKKizl7RV80W7SbTshpmPt"

arava:
  log-to-elasticsearch: true
  search:
    max-similar-results: 20
    indexer-thead-count: 10
logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE

elasticsearch:
  host: ""
  port: 9200
  protocol: http
