
spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
    default-property-inclusion: non_null
  datasource:
    url: jdbc:postgresql://localhost:5432/arava
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        search:
          default_backend: fs
          automatic_indexing:
            synchronization:
              strategy: async
          backends:
            fs:
              type: lucene
              directory:
                type: local-filesystem
                root: ./data/lucene
  main:
    allow-bean-definition-overriding: true
jwt:
  secret: 268YXz7tkqYON3wpAfXFMIlDT8qmn4v01DvTllPIShKKizl7RV80W7SbTshpmPt
  expiration: 604800
  token-type: "Bearer"

arava:
  log-to-elasticsearch: false
  search:
    max-similar-results: 20
    indexer-thead-count: 10
logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE

elasticsearch:
  host: es.ndogga.com
  port: 443
  protocol: https
  username: elastic